#!/bin/bash

TARGET="fourtres.py"
ASSETS="logo.png stores.json"
INCLUDE=""

BUILD_DIR="fourtres.build"
BUILD_DIST="fourtres.dist"
DISTRO="dist"

for items in $ASSETS; do
  INCLUDE="$INCLUDE --include-data-files=$items=$items"
done

# Cleanup before compiling
echo Preparing dist folder
if [ -z $BUILD_DIST ]; then
  echo $BUILD_DIST not found, proceed
else
  rm -rf $BUILD_DIST
fi
if [ -z $DISTRO ]; then
  echo $DISTRO not found, proceed
else
  rm -rf $DISTRO
fi

# Compile the file
python -m nuitka --standalone --enable-plugin=tk-inter $INCLUDE $TARGET 

# Cleanup build files
echo Cleanup build files
mv $BUILD_DIST $DISTRO
rm -rf $BUILD_DIR
