#!/bin/bash

VERSION="1.0.0"
TARGET="fourtres.py"
ASSETS="./img/logo.png ./img/logo0.png ./img/logo1.png ./img/logo2.png ./img/logo3.png ./img/logo4.png ./img/logo5.png ./img/logo6.png ./img/logo7.png ./img/logo8.png ./img/logo9.png ./img/icon.ico"
ICONFILE="./img/icon.ico"
INCLUDE=""

BUILD_DIR="fourtres.build"
BUILD_DIST="fourtres.dist"
DISTRO="dist"

for items in $ASSETS; do
  INCLUDE="$INCLUDE --include-data-files=$items=$items"
done

# Cleanup before compiling
echo Preparing dist folder
if [ -z $BUILD_DIST ]; then
  echo $BUILD_DIST not found, proceed
else
  rm -rf $BUILD_DIST
fi
if [ -z $DISTRO ]; then
  echo $DISTRO not found, proceed
else
  rm -rf $DISTRO
fi

# Compile the file
python -m nuitka --standalone \
                 --enable-plugin=tk-inter \
                 --windows-icon-from-ico=$ICONFILE \
                 --product-version=$VERSION \
                 $INCLUDE $TARGET 

# Cleanup build files
echo Cleanup build files
mv $BUILD_DIST $DISTRO
rm -rf $BUILD_DIR
